#!/bin/bash

MOD_CDO="gcc/4.7.2 intel/13.0.1 openmpi/1.8.1 NETCDF/4.1.3 HDF5/1.8.10 UDUNITS/2.1.24 CDO/1.7.0"

MOD_NCO="NCO/4.6.1"

F_GG_00="ICMGGa09i+000000"

echo
module load ${MOD_CDO}
echo


fm="mask_ifs_gr.nc"

#alias grib_info='cdo -t ecmwf sinfov'
#alias grib2nc='cdo -R -t ecmwf -f nc copy '
#alias grib2nc_gr='cdo -t ecmwf -f nc copy '

rm -f *.nc

# To netcdf Gauss-Reduced:
#cdo -t ecmwf -f nc -r selvar,LSM ${F_GG_00}  LSM_${F_GG_00}_gr.nc

#cdo -R -t ecmwf -f nc setmisstoc,0 -ifthenc,1 -gec,0.5 -selvar,LSM  ${F_GG_00}  LSM_${F_GG_00}_R01.nc
cdo    -t ecmwf -f nc setmisstoc,0 -ifthenc,1 -gec,0.5 -selvar,LSM  ${F_GG_00}  tmp.nc

module rm ${MOD_CDO}

module load ${MOD_NCO}

ncecat -O tmp.nc  -o tmp.nc

ncrename -d time,y -d rgrid,x tmp.nc

ncks -O -x -v time tmp.nc -o tmp.nc

ncwa -O -a record tmp.nc -o ${fm}

ncrename -v LSM,Amsk ${fm}

# Attribute variable
for ga in "long_name" "code" "table" "grid_type" "cell_methods"; do
    ncatted -h -O -a ${ga},Amsk,d,c, ${fm}
done


rm -f tmp.nc

# * A640.msk and L640.msk are identical and have 0 on the ocean right.
# * R640.msk is the oposite (1 on the ocean) ?
ncap2 -O -s "Lmsk=Amsk"    ${fm} -o ${fm}
ncap2 -O -s "Rmsk=float(1.-Amsk)" ${fm} -o ${fm}


for cc in A L R; do
    ncrename -v ${cc}msk,${cc}640.msk ${fm}
done






# Attribute global
for ga in "history" "NCO" "CDO" "CDI" "institution" "Conventions" "nco_openmp_thread_number"; do
    ncatted -h -O -a ${ga},global,d,c, ${fm}
done
ncatted -h -O -a About,global,o,c,"Generated by Laurent Brodeau / brodeau@gmail.com" ${fm}





exit
# -f nc4c -z zip
# cdo –R –f nc4c –z zip –t ecmwf  setmisstoc,0 –ifthenc,1 –gec,0.5 –selvar,LSM “ICM-file-with-172” lsm_IFS_N…



# Regular to get lon and lat:
#cdo -t ecmwf -f nc copy ${F_GG_00}  ${F_GG_00}_gr.nc
#cdo -R -t ecmwf -f nc copy ${F_GG_00}  ${F_GG_00}.nc